const categories= [
  "Action and Adventure",
  "Biography",
  "Children's",
  "Classic",
  "Comedy",
  "Crime",
  "Drama",
  "Fantasy",
  "Historical Fiction",
  "Horror",
  "Mystery",
  "Philosophy",
  "Poetry",
  "Political",
  "Religious",
  "Romance",
  "Satire",
  "Science Fiction",
  "Self-Help",
  "Short Stories",
  "Suspense and Thriller",
  "Technology and Science",
  "Travel",
  "Western",
  "Young Adult",
];

export {categories};